### PR TITLE
bumped to master

### PR DESCRIPTION
**Pull request by teto**
I couldn't use hie anymore because it was expecting ghc683 which got removed from nixpkgs-unstable and then trying to pass compiler ghc864, it would complain because I think the expected ghc parameters changed. It' still compiling locally hopefully it works fine.

### CODE REVIEW

**Comment by teto** [comment]
ghc got updated in 68be6bbc31351a4cf5b6431d746dc390ed29c16c.

Here is what I get with latest nixos-unstable:
```
error: while evaluating the attribute 'nativeBuildInputs' of the derivation 'ghc-shell-for-netlink-pm-1.0.0' at /home/teto/nixpkgs/pkgs/development/haskell-modules/make-package-set.nix:301:9:
while evaluating 'getOutput' at /home/teto/nixpkgs/lib/attrsets.nix:464:23, called from undefined position:
while evaluating anonymous function at /home/teto/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:125:17, called from undefined position:
while evaluating anonymous function at /nix/store/r1kpqk284ajf6xfw4h8cg1yn4sq920rh-source/ghc-8.6.nix:3:1, called from /home/teto/mptcpnetlink/hs/shell-test.nix:39:10:
while evaluating 'override' at /home/teto/nixpkgs/lib/customisation.nix:73:20, called from /nix/store/r1kpqk284ajf6xfw4h8cg1yn4sq920rh-source/ghc-8.6.nix:39450:4:
while evaluating 'makeOverridable' at /home/teto/nixpkgs/lib/customisation.nix:67:24, called from /home/teto/nixpkgs/lib/customisation.nix:73:29:
anonymous function at /home/teto/nixpkgs/pkgs/development/compilers/ghc/8.6.4.nix:1:1 called with unexpected argument 'initialPackages', at /home/teto/nixpkgs/lib/customisation.nix:69:12
```

**Comment by teto** [comment]
Finished compiling: might not be a good thing to merge but at least, it works on current nixos-unstable.

**Comment by domenkozar** [comment]
I'd prefer to use a stable release, @alanz is that planned soon? :)

**Comment by alanz** [comment]
We aim to do a release around the 1st of every month, which is sort of stable

**Comment by domenkozar** [comment]
#55

**Pull request closed without merging**
